### ISSUE TITLE
exception on ieb

### ISSUE THREAD

**Issue by eyalk5** [hgiesel/vim-motion-sickness#15] opened 2019-06-17 20:37 UTC
"~/vimpy3/plugged/vim-netranger/pythonx/netranger/Vim.py" 197L, 5237C
Error detected while processing function sickness#textobj#expression#motion[45]..<SNR>141_MatchOpenCloseDelims:
line    6:
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary
E712: Argument of count() must be a List or Dictionary

I am on neovim v0.3.1.1 with Oni

**Comment by hgiesel** [comment] 2019-06-21 14:07
Can you post the the text that caused it? In the following form:

Text:
`Hello w<cursor>orld`

Do:
`diw`

**Comment by eyalk5** [comment] 2019-06-21 21:39
Well, I think it happens every time I do ieb.

But just as an example:

     nmap  <C-/> :let g:EasyMotion_add_search_history=1<CR><Plug>(easymotion-sn)

Where ^ is cursor

     nmap  <C-/> :let g:EasyMotion_add_search_history=1<CR><Plug>(eas^ymotion-sn)

And do: cieb

**Comment by hgiesel** [comment] 2019-06-22 07:02
Hm, I can't reproduce the error, but I'll have another look at it.
On another note: `ieb` is probably not what you want. `ieb` evaluates to just `ab` in this context. This is becomes it imitates the `dsf` from vim-surround or vim-sandwich. what you want is either `1aeb` to select `g:EasyMotion_add_search_history=1<CR><Plug>(eas^ymotion-sn)`, or `3ieb`, to select `<Plug>(eas^ymotion-sn)` (3 alternating components of word / nonword characters (also see `:h iskeyword`)

**Comment by hgiesel** [comment] 2019-06-22 08:42
Okay, I found the issue. I test motion-sickness with the latest neovim release, which currently is 0.3.7. At some point between 0.3.1 (your version) and the current version they must have added support for strings in the `count()` function. The error will be fixed, if you use the current version (or at least the one which added support for that).

**Closed as completed by hgiesel** 2019-06-22 08:42 UTC
